### ISSUE TITLE
[configuration issues] TypeError: self.ensureSlug is not a function

### ISSUE THREAD

**Issue by dcramirezo-aesop** [apostrophecms/apostrophe-workflow#162]
Hi there,

I'm having issues when trying to configure Apostrophe Workflow on my site. When executing the task:

`node app apostrophe-workflow:add-missing-locales --live`

the following error appears:

`TypeError: self.ensureSlug is not a function
at Object.self.testInsertPermissions (../../aln-email-layout-tool/node_modules/apostrophe-workflow/lib/modules/apostrophe-workflow-docs/index.js:38:14)
    at Object.self.docBeforeInsert (../../aln-email-layout-tool/node_modules/apostrophe/lib/modules/apostrophe-docs/lib/api.js:560:10)
    at Immediate.<anonymous> (../../aln-email-layout-tool/node_modules/apostrophe/index.js:427:20)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)`

Does anyone know how to fix this? 

Thanks,
D

**Comment by boutell** [comment]
Added in apostrophe 2.43.0. Update your apostrophe module. Keep in mind that because of package-lock.json you must explicitly `npm update` to get new versions of things.
